project:
  output-dir: _output

toc: false
number-sections: true
bibliography: references.bib
csl: chicago.csl
colorlinks: true
date: last-modified
date-format: long

format:
  html:
    css: styles.css
    html-math-method: katex
  pdf:
    documentclass: article
  docx:
    reference-doc: custom-reference-doc.docx