---
title: "The implication of the aggressive emission target on the Indonesian electricity sector"
author:
  - name: Krisna Gupta
    id: kg
    orcid: 0000-0001-8695-0514
    email: imade.krisna@poltekapp.ac.id
    affiliation: 
      - name: Politeknik APP Jakarta
        city: Jakarta
        url: www.poltekapp.ac.id
abstract: > 
  The pledge to reduce emission has reached a new height globally, and Indonesia is no exception. According to Indonesia's latest NDCs, it vowed to reduce emission by 31.9% to 43.2%. One of the key for Indonesia to reduce its emission is electrification, which makes greening the grid a priority for the Indonesian government. However, Indonesia has been relying heavily on coal while the growth of renewable is slow. A linear optimization technique show that cleaning the indonesian electricity sector from coal leads to a potential increase in cost by 37%. The key to reduce this cost increase is by enabling the Indonesian independent power producers, which grow their electricity generation much faster than the state owned company. The government must improve the efficiency of procurement, improve its pricing, and forego local content requirements, if it wants to achieve its emission target.
citation: 
  container-title: Working paper
#  volume:  
#  issue:  
#  doi: 
jupyter: python3
execute: 
  echo: false
format: 
  html: 
    code-fold: true
#    html-math-method: mathml
    theme: united
    mainfont: serif
  pdf:
    toc: false
    number-sections: true
    colorlinks: true
    documentclass: scrartcl
    papersize: a4
  docx:
    toc: false
    number-sections: true
---

## Introduction

The importance to ramp up efforts to decarbonize Indonesian energy sector just reached a new height.The Indonesian government joined the global bandwagon of committing to a more emission reduction target. Just before the 27$^th$ session of the Conference of the PRties (COP27), The Indonesian government comitted to a more aggresive reduction of greenhouse gas (GHG) emission by 31.90% by 2030, or by 43.20% with the help of other countries [@budy].

For the energy sector, the Indonesian government pledged to reduce the emission from energy sector by 12.5% or by 15.5% with the global help. Energy sector remains an important emitter of GHG in Indonesia. While the target is not as aggresive as the forestry and land use sector, the energy sector is going to account for 58.17% of the total emission in 2030 under the business as usual (BAU) projection [@budy].

In the energy sector, electricity generation will play an even greater role going forward. The latest data suggests the Indonesian electricity sector to provide around 20% of the Indonesian total energy needs [@wahyuni;@moef]. This share, however, will increase as the Indonesia nudge toward electrification of cooking and transportation [@budy]. Meanwhile, the Indonesian electricity sector aimed to have zero emission by 2040, far quicker than energy and other sectors in general [@ember1;iea]. Greening the Indonesian grid, therefore, become one of the most important challenge the Indonesian government must met to achieve the emission target [@paul2;@budy;@iea;@ember1].

This paper aims to discuss the cost of the Indonesian electricity transition toward renewable under the government's aggressive emission target. Linear optimization assume perfect substitution with constraints is chosen as the preferred method to project the cost of electricity. Linear optimization is suitable for a perfect substitution grid [@cowell;@quant]. Moreover, the method is simple enough to replicate and provides a useful to make projection and plans given a proper parameterization and constraints.

Results suggests that the Indonesian government will be able to reach its NDC targets without and additional cost to the consumer. This is true as long as Indonesia cover the larger cost of renewables by replacing other fossil fuel source with coal. A grid without coal, as envisioned by the Indonesian government in 2040 [@ember1;@memr2], would increase the cost of electricity by 37%, a non-trivial increase. This increase must be abated by either a significant reduction of renewable prices, or a subsidy.

Further discussion is made on the viability of this transition. The most promising renewable in Indonesia so far is solar PV. However, the adoption speed is hindered by incompetent bureaucrats and local content requirement imposed on government projects. Also discussed is the role a newly regulated carbon market in Indonesia. This is, however, also have its own challenges.

Enabling the growth of Independent Power Producers (IPP) is key since their renewable growth far outpaced the state owned electricity company. The government must improve its bureaucratic efficiency so procurements can be conducted much faster with a better certainty. Electricity price needs to be made more flexible to cater for niche off-grid consumers. Lastly, nudging local industries with local content requirement hinders the adoption rate of renewables, and one has to give.

The next section discusses the literature around the new emission target and Indonesia's electricity sector. Section 3 explains the method of choice. Section 4 discusses the results and its implications toward greening the grid, and section 5 concludes.

## Indonesia electricity outlook

Just prior the COP27, Indonesia submitted an optimistic document describing its updated nationally determined contributions (NDCs) [@budy]. Indonesia pledged to reduce total emission by 31.9% under CM1 and 43.2% under CM2[^1]. Meanwhile, the energy sector is pledged to reduce emission by 12.5% and 15.5% under CM1 and CM2 respectively.

The strategy to achieve this target relies heavily on electrification of energy [@iea]. According to the Indonesian government's roadmap, Indonesia would supply 25% of the total energy from renewables by 2030 [@budy]. On the demand side, it projects a 5.5 million of electric cars, 8.5 million of electric motorcycles, and 5 million households with induction cookers in in 2030 [@budy]. Indeed, electrification is an important part of the Indonesian effort to fulfill its NDCs.

Indonesians are among a relatively smaller consumers of electricity, and its use is concentrated mostly in Java island [@paul1]. The electricity market is dominated by the state-owned firm, *Perusahaan Listrik Negara* (PLN), in both distribution and generation [@budy]. While an Independent Power Producer (IPP) is allowed to generate electricity, they must sell it to PLN as the sole distributor of electricity.

Electricity pricing is highly regulated by the government [@paul1]. The electricity tariff schedule is layered and differentiated between consumers. The tariff schedule is separated by households, business, and industry. For each group, tariff is discriminated further by its maximum volt-ampere. Moreover, households are often the highest receiver of subsidy and consequently pay the lowest on electricity compared to businesses and industries [@paul1].

PLN is central to Indonesia's electrification strategy. Renewable is projected to be the source of 52% of PLN's electricity generation [@memr2]. However, the road toward greening the greed seems slow. According to @pln statistics, the percentage of renewables generated by PLN in 2021 is only 8% (see @tbl-pln). A large majority of the renewable electricity is sourced by hydropower and geothermal. Additionally, the growth of renewable electricity since 1998 (31.2%) is dwarfed by PLN's total capacity growth (144.08%). Indeed, the majority of PLN's capacity growth is from coal, defying the global trend [@ember;@paul1].

| source | 1998 (GWh) | 2021 (GWh) |
|------|------|------|
| Hydro    | 9,649.00   | 11,869.30    |
| Geothermal |  2,616.80  | 4,216.17    |
| Solar    | -    | 5.63    |
| Wind     | - | - |

: The amount of renewable electricity by PLN (GWh) {#tbl-pln}

The slow growth of renewables stem from the Indonesian's reliance on coal [@budy; @paul2]. Coal is cheap, abundant, and reliable, reducing the incentives to look for alternative. Moreover, PLN's pricing is highly regulated by the government. Meaning, already relatively low, Indonesian electricity price cannot be raised by PLN when it is needed. The Indonesian government also would like to limit subsidy, leading to further reliance on coal [@budy].

Indonesia's renewables are coming mostly from hydropower and geothermal. Unfortunately, the two sources are growing very slowly, mainly due to a slow land acquisition, especially geothermal [@paul2]. Indonesia's wind potential is not promising, leaving solar Photovoltaic (solar PV) as the best soource of renewable growth [@paul2;@iea]. Indonesia has a good potential for solar energy and may utilize floating solar panels above waters [@blakers]. The ecological impact of blocking the sun on water may still need studies.

While the PLN's renewable accounts for only 8% of total PLN generation, renewable accounts for 17% of total general electricity generation [@ember]. This majority of the discrepancy may come from IPPs. In 2021, around 36.79% of the Indonesian electricity is generated by IPPs, which is only accounting for 3.78% of total generation in 1998. Moreover, it is projected that IPP would provide 64% of electricity in 2030 [@memr2]. This shows the importance of IPPs for improving the Indonesian renewable electricity capacity.

The popularity of IPP rises in 2013 when the government announced reverse auction for solar panel [@paul2]. In 2021, out of 225 megawatts solar energy capacity in Indonesia, only 21.34 MW (9%) belongs to PLN. However, a limitation imposed on foreign involvement in both investment and product components as well as low administrative capacity slow down the growth [@paul2]. Moreover, some projects are too expensive for PLN. Since it does not control price, it cannot impose a premium pricing for some expensive IPP projects. Lastly, an overcapacity of coal electricity leads PLN to slow down its third-party purchases of renewables. Direct competition with PLN's own asset is also a known problem in supporting renewable electricity [@paul2].

In short, financial capacity needs to be improved. PLN's lack of pricing prower and subsidies limit its capacity to invest and absorb energy invested by third party generators. It may need to early-retire a large number of coal powerplant. The government also need to improve grid infrastructure and general project infrastructure to lower the cost of building new renewable generators and its transmission. According to @memr, Indonesia needs Rp 3,500 trillion ($0.23 trillion) to achieve its NDCs targets.

Internal financing is constrained considering the limitation of Indonesia's domestic saving and fiscal capacity [@gupta;@budy]. One way to improve this situation is to find alternative source of funds like the carbon tax. In 2021, The Indonesian government issued regulations for implementing an emission trading system (ETS) [@budy]. The idea is the government will set a carbon-cap for firms to emit. Firms who emit less than their allowance can sell those quota to firms plan to emit more than its carbon-cap. If a firm emits too much without buying an allowance, it will be taxed at the ETS market price.

A pilot project in 2021 results an average carbon price of 2 USD per tonne of carbon dioxide and a proposed a 30 IDR/kgCO2 carbon tax [@cnbc]. This pricing translates to around an extra 0.6 IDR/KWh addition to electricity price. The official ETS market was implemented on September 2023 by IDXCarbon. The Resulting price was around 63 IDR/kgCO2 [@cnbc2,@solum], which translated roughly to 1.2 IDR/KWh. For comparison, The Chinese ETS resulted in around 5 USD per tonne of carbon dioxide, while the price of carbon in the European Union (EU) ETS is 96 USD in 2023 [@wb].

The government plans to reduce the carbon-cap every year. In a perfectly functioning carbon market, The cap reduction will reduce the carbon-cap available to buy, which will push carbon price (and consequently the carbon tax) upwards. If the carbon price is high enough, it will incentive firms to either invest in green energy, reduce its energy consumption altogether, or pay the taxes under the high ETS price. The latter would help the government finance the desired investment in green energy.

Indonesia electricity consumption is only a quarter of the world average [@paul1], many of them are poor[^2]. As Indonesia aspires to grow faster, the consumption of electricity needs to increase. A low carbon quota and an electricity price that's too high may discourage access to electricity and increase inequality [@pearse]. According to a simulation by @yuve, developing renewable electricity may increase poverty incidence in Indonesia by 10-13 percentage points.

## Simulation

This paper proposes a linear optimization method to simulate the state of Indonesian electricity given a changes in carbon quota and prices. The strength of linear optimization method lies in its simplicity in execution and in explaining the resulting output [@quant]. A fully linear system also warrant a solution, and can be adjusted easily by parameterization or additional equations.

A fully linear system may not represent well the industry's electricity supply in general. However, if direct competition among different supplier as in [@paul2] is indeed holds back renewable adoptions, it is likely the perfect substitution be feasible. In the presence of additional contraints, we can poses a restrictions on the parameters.

This section focuses on building the system, parameterization, and scenarion descriptions.

### The linear system

Let $Q$ be a quantity produced by the Indonesian economy which is nested with a leontief production function with energy. That is, $Q=\min (F(.),G(\omega))$, where $F$ is a combination of factors such as capital and labour. Let $\Omega$ be the total energy required to produce $Q$ in one period. The economy produces $\omega$ with a fully substitute sources:

$$
\omega=w_a+w_b+w_g
$$

where $w_a$ is the amount of clean energy used, while $w_b$ and $w_g$ are coal and gas respectively. if $p$ is a vector of prices of the three sources of energy and $w \in \{w_a,w_b,w_g\}$, producers in the economy are faced with a cost minimization problem to produce $Q$, and by extension, $\omega$.

$$
\begin{aligned}
\min_{w} \ &  p \cdot w \\
\mbox{subject to } \ & \omega=w_a+w_b+w_g
\end{aligned}
$$

In this setting, $\omega$ is taken as exogenous as the consequence of the Leontief production nest. That is, factor of production is the driver of $Q$ and consequently $\omega$. This assumption allows the use of the cost minimization technique and observe the cost impact of idiosyncratic shock to prices or $\omega$ (and $Q$ by extension) if one needs to change the total output [@cowell].

We improve this setting by adding emission constraints. We limit total emission coming from the use of each source of energy. Next, we limit how much the total combination of emissions from these sources is allowed. This variable, then, can be set exogenously to reflect the government's preference of emission.

Let $a,b,g$ be parameters which reflect emission generated per megawatt hour by $w_a, w_b, w_g$ respectively. Let $\varepsilon$ be the total emission generated by the Indonesian electricity sector, Then the total emission generated by these sources is:

$$
aw_a+bw_b+gw_g=\varepsilon
$$

With the above emission constraint, we have a complete linear system as follows:

$$
\begin{aligned}
\min_{W} \ &  p \cdot w \\
\mbox{subject to } \ & w_a+ w_b+ w_g \ge \omega \\
 & aw_a+bw_b+gw_g \le \varepsilon \\
 & w_a,w_b,w_g \ge 0\\
\end{aligned}
$$

Cost minimization allows for the calculation of compensating variation, which is the compensation for the consumer to maintain the same level of electricity consumption under an economic shock [@cowell]. The shock of the model can come from two exogenous variables $p$ which reflects a carbon tax, or $\varepsilon$ which reflects how much carbon quota is given in the economy as a whole.

### parameterization

The next step is to find a representative parameter. @pln is the main source of $\omega$ and $p \cdot w$. Perusahaan Listrk Negara (PLN) statistics is reliable since it is the sole distributor of electricity in Indonesia. According to @pln, Indonesia generates 289,470.57 Gigawatt hour (GWh) in 2021. From those, around 60% are produced using coal as its main source and around 23% by some mixes of fossil fuels. Only 17% is generated by renewables, mostly hydroelectric [@ember;@pln].

@pln also contains data on prices per Kilowatt hour (KWh) of electricity based on sources.  The prices per KWh of solar is used for $p_a$ since solar PV has the most promising renewable growth at the moment. The price for coal-based electricity $p_b$ is half as expensive as $p_a$ accodring to @pln. Meanwhile, other fossil fuel is priced very close to $p_a$, as in @pln.

Lastly, emission factor $a,b,g$ are calibrated from @febijanto10 and @jrc. The number of emission factor varies between countries and in different reports, and emission factor in this paper tries to balance those differences. The emission factor is set to be very low (from procuring the photovoltaic panels). The emission factor for coal is ten times from the renewable, while other fossil fuels is set to be 70% of coal. Total emission generated by the electricity sector is calculated based on the emission factor and how much energy source is used by the sector.

### Scenarios

Various scenarios can be tested on this model, but 7 scenarios stand out. Case 1 is the status quo. That is, the source is restricted to fit the current share of electricity by source according to @ember. That is, 17% renewables, 60% coal and 23% from other fossil fuels. This scenario serves as parameterization for total emission emitted by the electricity sector given emission factor. This exercise also provides a baseline cost of the status quo generation.

Case 2 is the cost optimization given the same electricity generated and the same total emission from case 1. This scenario shows what the model would tell us how much share of electricity would be if the sector is fully substitute with no switching cost. One can argue the case for long-run generation if there is no emission targeting in place. That is, the country adjust the electricity generation solely for accessibility. Looking at how the coal progresses in Indonesia, this scenario would likely shows us a total coal domination if it is not restricted.

The carbon tax scenario is the case 3. The 50 IDR/kgCO2 is imposed as a carbon tax. This tax is extremely low, however, which translates to 0.6 IDR/KWh. Since the price of electricity in 2023 is around 1,400 IDR/KWh, the proposed carbon tax is extremely trivial. To show an actual impact of the carbon tax, a carbon tax equivalent to 50% of the electricity price is imposed on coal.

Case 4 and 5 poses restrictions on the total emission generated. The goal from CM1 and CM2 in the NDCs is implemented on the model. That is, case 4 and 5 imposes a restriction on total emission to be 12.5% and 15.5% lower than case 2 respectively. The goal of these exercise is to show how much more expensive electricity is under these scenarios, on top of the cost to make the switch in the first place.

Next, we would like to know how much the cost and emission generated under the government's plan for the PLN. According to @memr2, Indonesia will have 52% of its electricity to be sourced from renewables. Case 6 tests this scenario by limiting the lower bound of renewable electricity use by 52% and see how much emission it reduce and how much will it will cost to operate this distribution of electricity source.

The last 2 cases demonstrate the situation when Indonesia has successfully implemented its strategy as explained by @ember1. That is, case 7 shows the situation when Indonesia is successfully reduced the use of coal to 0%, while case 8 shows the situation when Indonesia implements 100% renewable electricity, as projected by 2040 and 2050 respectively [@ember1]. Case 7 is implemented by restricting the upper bound of $w_b$ by 0, while case 8 bounds electricy by 100%.

All of these cases are summarized in @tbl-scenarios. These 8 cases are exercised as a benchmark for possible emission and cost of the Indonesian electricity generation. Moreover, these 8 cases also show the flexibility of the model in projecting cases by altering different exogenous variables. These exercises provides a good comparative static which will be discussed in the next section.

| case | description | model setting |
| --- | ---------- | ------------- |
| 1 | status quo | restricting the current share of generation. |
| 2 | current emission, optimized | case 1 without source restriction. |
| 3 | carbon tax | Same emission limit but with a carbon tax |
| 4 | CM1 | same prices but a 12.5% emission reduction |
| 5 | CM2 | same prices but a 15.5% emission reduction |
| 6 | New RUPTL | case 2 with 52% renewables |
| 7 | Zero coal | case 2 with 0% coal |
| 8 | Fully renewable | case 2 with 100% renewables |

: scenario descriptions {#tbl-scenarios .hover .striped}

## Results and discussions

```{python}
#| warning: false
#| error: false
#| echo: false
import pandas as pd
import numpy as np
from scipy.optimize import linprog
from scipy.optimize import fsolve

class carbon:
  r"""
  implements the perfect substition of energy usage with prices and emission as the contraints. Note: the default emission is calculated by share of electricity generated times its emission factor.
  
  the cd() function, meawhile, proposes a cobb-douglass function for electricity generation. However, it hasn't been showing a good iteration regarding the parameterisation. More data is needed to make better calibrations.
  """
  
  def __init__(self, omega=289470570.0,  #MWh
                     e=225208103460.00,   #KgCO2
                     pa=1284440,         #Rp/MWh
                     pb=667880,          #Rp/MWh
                     pg=1247930,         #Rp/MWh
                     a=100,              #KgCO2/MWh
                     b=1000,             #KgCO2/MWh
                     g=700,              #KgCO2/MWh
                     ba=(0,None),
                     bb=(0,None),
                     bg=(0,None)
                     ):
    self.omega,self.e,self.pa,self.pb,self.pg,self.a,self.b,self.g=omega,e,pa,pb,pg,a,b,g
    self.ba,self.bb,self.bg=ba,bb,bg
    
  def hasil(self):
    omega,e,pa,pb,pg,a,b,g=self.omega,self.e,self.pa,self.pb,self.pg,self.a,self.b,self.g
    ba,bb,bg=self.ba,self.bb,self.bg
    # Construct parameters
    c_ex1 = np.array([pa,pb,pg])

    # Inequality constraints
    A_ex1 = np.array([[-1, -1,-1],
                  [a,b,g]])
    b_ex1 = np.array([-omega,e])

    bounds_ex2 = [ba,
                  bb,
                  bg]

    # Solve the problem
    # we put a negative sign on the objective as linprog does minimization
    res_ex1 = linprog(c_ex1, A_ub=A_ex1, b_ub=b_ex1,bounds=bounds_ex2)
    return res_ex1
  
  def biaya(self):
    omega,e,pa,pb,pg,a,b,g=self.omega,self.e,self.pa,self.pb,self.pg,self.a,self.b,self.g
    h=self.hasil()['x']
    v=np.array((pa,pb,pg))
    c=(h @ v)/1e12
    return c
#    return print(f'total biaya pembangkit listrik adalah {c} triliun rupiah')
  
  def emisi(self):
    omega,e,pa,pb,pg,a,b,g=self.omega,self.e,self.pa,self.pb,self.pg,self.a,self.b,self.g
    h=self.hasil()['x']
    v=np.array((a,b,g))
    m=h @ v
#    return print(f'total emisi adalah {m} kgCO2')
    return m
    
  def summary(self):
    omega,e,pa,pb,pg,a,b,g=self.omega,self.e,self.pa,self.pb,self.pg,self.a,self.b,self.g
    m=self.emisi()
    c=self.biaya()
#    lal=print(f'total biaya pembangkit listrik adalah {c:.2f} triliun rupiah')
#    lel=print(f'total emisi adalah {m:,.2f} kgCO2')
    lal=print(f'The total cost is {c:.2f} trillion IDR or {c/omega*1e9:,.2f} IDR/KWh')
    lel=print(f'The total emission is {m:,.2f} kgCO2')
    sumber=('renewables','coal','other fossil fuels')
    itung=self.hasil()['x']
    for i,j in zip(sumber,itung):
        print(f'Total electricity by {i} is {j:,.2f} MWh ({j/omega*100:.2f} %)')
    return lal
    return lel
  
  def cd(self,al=.1,
              be=.6,
              ga=.3,
              b1=1e6,
              b2=1e6,
              b3=1e6,
              ):
    omega,e,pa,pb,pg,a,b,g=self.omega,self.e,self.pa,self.pb,self.pg,self.a,self.b,self.g
    def func(w):
      omuga=108558478
      return [w[0]-omuga*((pb*al/pa/be)**be)*((pg*al/pa/ga)**ga),
              w[1]-omuga*((pa*be/pb/al)**al)*((pg*be/pb/ga)**ga),
              w[2]-omuga*((pa*ga/pg/al)**al)*((pb*ga/pg/be)**be),
              a*w[0]+b*w[1]+g*w[2]-e]
    root = fsolve(func,[b1,b2,b3,1],xtol=0.01)
    root
    return root
  
  def hasilcd(self):
    omega,e,pa,pb,pg,a,b,g=self.omega,self.e,self.pa,self.pb,self.pg,self.a,self.b,self.g
    sumber=('renewables','coal','other fossil fuels')
    itung=(self.cd()[0],self.cd()[1],self.cd()[2])
    c=(pa*self.cd()[0]+pb*self.cd()[1]+pg*self.cd()[2])/1e12
    m=a*self.cd()[0]+b*self.cd()[1]+g*self.cd()[2]
    for i,j in zip(sumber,itung):
        print(f'Total electricity generated from {i} is {j:,.2f} MWh ({j/omega*100:.2f} %)')
    lal=print(f'The total cost of electricity generation is {c:,.2f} trillion IDR')
    lel=print(f'The total emission is {m:,.2f} kgCO2')
    return lal
    return lel
    
```

The 7 cases is shown below.

Case 1: status quo

```{python}
case1=carbon(ba=(0.17*289470570.0,None),bg=(0.23*289470570,None))
case1.summary()
```

case 2: minimized cost, same emission (no target)

```{python}
case2=carbon()
case2.summary()
```

case 3: carbon tax
```{python}
case3=carbon(pb=667880*1.5) # harga asli 667880, dikasi tax 600/mwh wkwk
case3.summary()
```

case 4: CM1
```{python}
case4=carbon(e=217459744720.0-(217459744720.0*.125))
case4.summary()
```

case 5: CM2
```{python}
case5=carbon(e=217459744720.0-(217459744720.0*.155))
case5.summary()
```

case 6: new RUPTL
```{python}
case7=carbon(ba=(.52*289470570.0,None))
case7.summary()
```

case 7: 0% coal
```{python}
case6=carbon(bb=(0,0))
case6.summary()
```

case 8: 100% renewable
```{python}
case6=carbon(ba=(289470570.0,None))
case6.summary()
```

In general, it is clear that coal is the main choice for cost reduction. The high price relative to emission for other fossil fuels does not justify using it at all in the optimization process. The cost-emission trade-off is basically a choice between coal and renewable sources. To reflect the status quo, some constraints need to be imposed on the variables.

The final results of the simulation may not fully reflect the real world price. However, comparisons between cases is still valid since a difference of a linear system are constant. That is, while the prices of electricity in each cases may not exactly the same with the real world, the difference of prices between cases should still be useful. Additionally, the model prediction can still be improved with parameterization.

Since case 1 is the status quo situation, we can use case 1 as the baseline. The electricity mix of case 1 reflects the mix from @ember. This combination, according to the simulation, emits around 225,208,103,460 kgCO2 which is priced 906.11 IDR/KWh[^3]. Meanwhile, case 2 shows that the electricity mix in case 2 gives a 819.96 IDR/KWh, which is 9.5% cheaper given the same emission generated. This result is consistent with the long-run trajectory of Indonesian electricity mix towards coal since the early 2000s.

The electricity mix from case 3 is consistent with case 2. It seems that in this model, a 25% electricity generated from renewables is optimal to keep emission the same while dropping the more expensive fossil fuel altogether. According to this case, a tax equivalent to a 50% cost increase in electricity generated by coal translated into an 18.26% increase in the total cost of electricity compared to the baseline. Indeed, as long as the tax is not high enough, coal will still be preferable to other types of fossil fuel.

In the case 4 and case 5, the government is committed to the emission reduction by 12.5% and 15.5% reduction respectively, obeying its NDCs. To fulfill the CM1, Indonesia must increase the renewable in the electricity mix by 21 percentage points from the baseline, and 2.5 percentage points more to fulfill the CM2. Interestingly, the electricity cost in the case 4 is slightly lower compared to the baseline. Note that in case 4, the mix from coal differs only slightly compared to the baseline.

Next, let us turn to the case 6 which is the situation where the government has successfully hit their 52% renewable targets. Under this case, electricity price increases by 9.09% compared to the baseline. However, if the government is indeed able to hit this target, the emission from this mix is reduced by 31.62%, far lower than CM2 in the NDCs.

Under the zero coal target in 2040 (case 7), the price of electricity jumps significantly. The price is increased by 37.72%. Without coal though, the electricity mix is sourced solely by non-coal fossil fuels. This is already require less emission even without any renewable necessary.

Meanwhile, case 8 is the most ambitious, which is a 100% renewable electricity. The cost of electricity is virtually no difference than case 7, but the emission is extremely small. This emission comes from mainly manufacturing the solav panel and wind turbine.

It is clear from the result that coal is very important in minimizing cost. In fact, this simulation shows that coal is the key to achieve emission target without a large increase in electricity prices. A zero coal leads to an extremely high compensating variation of around 37%. The government needs to smoothen the increase by a subsidy, or repeat the success of the communication strategy in the 2010s to avoid protests [@paul1].

Note that the linear nature of this model leads to the use a constant cost of electricity. In reality, the price of electricity may change as its production increases. The levelized cost of electricity (LCOE) for solar PV has been declining by 88% from 2010 and 2021. @iea projects Indonesia's cost of solar electricity may be pushed down to 400-1,000 IDR/KWh in the future. If the reduction of price continue, the compensating variation may reduce and lower the cost of the energy transition.

However, the bottleneck may come from non-monetary cost. for example, land rights can be a constraint as well. Securing land rights has already become a problem for geothermal [@paul1]. If solar PV and wind has reached a certain level, land rights may potentially be a bottleneck. While cost per KWh has been an important indicator for planning electricity generation, how much area is needed per KWh may need to be considered as well.

Additionally, administrative cost can also be a hindrance. It has been well known that the Indonesian government's procurement of solar PV projects has been slow and uncertain [@paul2;@iesr]. Additionally, the local content requirement (LCR) imposed on the government's solar PV projects is also cited as a major bottleneck [@iesr]. While LCR for solar PV is imposed to help local manufacturing, it runs counter to the emission reduction targets.

Can the carbon tax and the ETS system helps with financing? According to @pearse, ETS has often proved to be unsuccessful in reducing emission. While ETS often modeled by the assumption of a perfectly functioning market, it is often not the case. ETS is prone to political intervention by firms and the government often unable to correctly punish over-polluters. In the early implementation of the EU ETS, carbon price leads to 0 amid a quota oversupply [@pearse]. The jury is still out for Indonesia, but looking at various corruption cases in import quota license in trade in goods [@amanta;@gupta2], it is not promising.

There are trade-off the government is facing. First is the cost-emission trade-off. If renewable can scale very quickly, then retiring coal-based power plant may be delayed, or even desirable since it helps with lowering the cost. The incredible growth of IPP in the renewable electricity must be facilitated with more efficient bureaucracy and better certainties for solar PV projects. Lastly, the government may need to forego the LCR rule on solar PV, if it wants to reach the renewable goal as soon as possible.

It is also important to note the think of this results in the broader scheme of emission reduction. The largest emission reduction according to the Indonesian NDCs will come from the agriculture, forestry and land use sector. So far, forestry and land use in Indonesia has covered by the REDD+ scheme under a limited success [@hermawan;@indrajaya;@kim]. The success of a program like REDD+ relies on various issues like governance and evaluation[@pearse], which still need a lot of work, especially for the Indonesian government. [@shin;@goncalves;@goldstein]. If sectors outside of energy do not progress as expected, then the energy sector may have to pick up the pace.

## Conclusion

The Indonesian government latest NDCs shows a confident emission target. The Indonesian electricity sector is targeted to reduce emission by 12.5% by its own effort or 15.5% with the help of the international community. To achieve this, the Indonesian government vow to increase its share of renewable electricity up to 52% in 2030, free its electricity grid from coal by 2040, and become fully renewable in 2050. Considering how important electrification of energy in the Indonesian net-zero strategy, greening the grid become extremely crucial.

Using an linear optimization technique, it is shown that freeing the grid from coal would cost the Indonesian electricity consumer with 37% higher electricity tariff. This increase will really hurt Indonesian electricity consumption which already very low in international standard. On the other hand, to ensure an affordable electricity, Indonesia should keep its coal.

One option to compensate the increase in electricity price is to smoothen the price increase by providing a subsidy or increase the price discriminately. This would add more financial burden on top of the necessary 3,500 Trillion IDR to green the grid. Carbon tax and ETS can be one way to earn such funding. But judging from problems faced by other countries, it may left to be desired.

The other option is to keep the progressive reduction of solar PV's LCOE. The Indonesian independent power supplier already greening much faster than the PLN. The Indonesian government must keep up the momentum by facilitating them. Organize a better, more efficient procurement and purchasing agreement. Uncertainty must be reduced, especially in the contract design and land acquisition. Consider foregoing LCR, since the goal toward zero emission may be more important than supporting indigeneous solar PV industry.

## Bibliography {.unnumbered}

::: {#refs}
:::

[^1]: CM1 = Counter Measure 1 (without international support), while CM2 = counter measure 2 (with international support).

[^2]: 99.85% of PLN's customers are low voltage [@pln]

[^3]: data from @pln suggests the average cost of electricity in 2021 is 1,083.30 IDR/KWh